const { chromium } = require('playwright');

(async () => {
    const browser = await chromium.launch({ headless: false });
    const context = await browser.newContext();
    const page = await context.newPage();

    console.log('Navigating to http://localhost:8080...');
    await page.goto('http://localhost:8080', { waitUntil: 'networkidle' });
    await page.waitForTimeout(2000);

    console.log('Waiting for canvas to load...');
    await page.waitForSelector('#workflow-canvas');

    // Create Hero node directly via JavaScript
    console.log('\n=== Creating Hero Node via JavaScript ===');
    await page.evaluate(() => {
        if (window.app && window.app.addNodeAtCenter) {
            window.app.addNodeAtCenter('Hero');
        }
    });

    await page.waitForTimeout(1000);

    // Select the node via JavaScript
    await page.evaluate(() => {
        if (window.app && window.app.canvasRenderer && window.app.canvasRenderer.nodes.length > 0) {
            const node = window.app.canvasRenderer.nodes[0];
            window.app.canvasRenderer.selectNode(node);
            window.app.updatePropertiesPanel(node);
        }
    });

    await page.waitForTimeout(1000);

    // Take screenshot of properties panel
    console.log('Taking screenshot of properties panel...');
    const propertiesPanel = await page.locator('#properties-content');
    await propertiesPanel.screenshot({ path: 'hero-properties-v2.png' });

    // Check for Data source dropdown
    const dataSourceLabel = await page.locator('text=Data source').count();
    console.log(`Found "Data source" label: ${dataSourceLabel} times`);

    const dataSourceSelect = await page.locator('select[data-property="dataSource"]').count();
    console.log(`Found dataSource select: ${dataSourceSelect} times`);

    // Get the options from the dropdown
    if (dataSourceSelect > 0) {
        const options = await page.locator('select[data-property="dataSource"] option').allTextContents();
        console.log('Dropdown options:', options);

        if (options.includes('Not defined') &&
            options.includes('Generated by the agent') &&
            options.includes('Instructed with the prompt')) {
            console.log('✓ PASS: Hero node has correct dropdown options!');
        } else {
            console.log('✗ FAIL: Hero node dropdown options are incorrect');
        }
    } else {
        console.log('✗ FAIL: No dataSource dropdown found');
    }

    console.log('\n\nInspection complete! Check hero-properties-v2.png');
    console.log('Browser will stay open for 10 seconds...');

    await page.waitForTimeout(10000);
    await browser.close();
})();
